### ISSUE TITLE
Top headlines?

### ISSUE THREAD

**Issue by aaronchantrill** [ranahaani/GNews#10]
Nice!

There doesn't currently appear to be a way to get news stories without specifying a topic (key). Could I modify the function so if the user uses get_news() without a key, or passing None or the empty string, it just grabs the top stories from the main feed for your locale?

Do you support Category or Location based searches?

Thanks!

**Comment by ranahaani** [comment]
Great idea. I'll keep this on my list. This package support Location base search. you can get details from readme file.

**Comment by ranahaani** [comment]
Top headlines feature added
