### ISSUE TITLE
Only 8 topics are able to be queried 

### ISSUE THREAD

**Issue by josephswlee** [ranahaani/GNews#114]
Hi,

I noticed `gnews/utils/constants.py` defined TOPICS = ["WORLD", "NATION", "BUSINESS", "TECHNOLOGY", "ENTERTAINMENT", "SPORTS", "SCIENCE", "HEALTH"]. This does not match the available topics from [README](https://github.com/ranahaani/GNews#:~:text=Get%20news%20by%20major%20topic). Was this intentional or is there way you can query the topics outside of the TOPICS like 'FINANCE'?

Edit: I do see why only those topics were allowed. Is there way you can search specific keyword like `Artificial Intelligence` after searching by topic `TECHNOLOGY`?

**Comment by ranahaani** [comment]
New topics has been added 
https://github.com/ranahaani/GNews?tab=readme-ov-file#Get-news-by-major-topic
