### ISSUE TITLE
get_news stopped working

### ISSUE THREAD

**Issue by shorenewsbeacon** [ranahaani/GNews#27]
Been working on some code for past week and it had been working fine with get_news("topic") .
Stopped working earlier get_top_news() still works. Tried using other keywords for topic but still returns nothing.

Any debug help?

**Comment by highfrog** [comment]
Same thing happened to me, I think ip is being blocked because get_news(keyword) works again when I use a different ip.

**Comment by shorenewsbeacon** [comment]
16 hours later I have ran the code and it works again. Is there any way in future releases we could possibly have an error message presented that could point in the direction if it is a blocking issue or some other kind of issue?

**Comment by ranahaani** [comment]
@highfrog @shorenewsbeacon I checked `get_news` working fine. can you please share your search limit requests?
I'm just releasing a new version, which includes proxy, and some other amazing features. I will take care of error logs too.
Thanks

**Comment by ranahaani** [comment]
@shorenewsbeacon Added proxy support, also logs for error, install the latest version for latest features

**Comment by shorenewsbeacon** [comment]
@ranahaani 
  google_news.period = '3d'

  Thank you I will install the new version. Appreciate the quick action.
