### ISSUE TITLE
Problems about get full article in a docker container

### ISSUE THREAD

**Issue by aoelvp94** [ranahaani/GNews#30]
Hello. I have some doubts about this line https://github.com/ranahaani/GNews/blob/master/gnews/gnews.py#L86. I need to run GNews in a docker container by using Airflow in order to get information about articles. I got the following message:

```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
```

And then Airflow sent me a negative signal to fail my task.

**Comment by valorien** [comment]
I don't think the warning message is related to that specific line.
The `pip` issue should be resolved now that https://github.com/ranahaani/GNews/pull/34 is merged.
