### ISSUE TITLE
Issue on setting date range

### ISSUE THREAD

**Issue by plim001** [ranahaani/GNews#38]
Hi,

Below is the code provided, but I cant seem to set the date range 

![image](https://user-images.githubusercontent.com/98269427/178152613-eda60666-b23c-4d07-a6ef-70c47c136ee6.png)

**Comment by ranahaani** [comment]
Issue has been fixed https://github.com/ranahaani/GNews/pull/41

**Comment by gianandreabertello** [comment]
> Issue has been fixed #41

Period is working with the new approved code
But I cannot make the start_date end_date working. I tried both the ("2021, 7, 11") format and (2021, 7, 11) 
Can you help me? Thank you
