### ISSUE TITLE
I got a lot less links than earlier in the last month / 2 months?

### ISSUE THREAD

**Issue by Colder347** [ranahaani/GNews#43]
Hi,

I use GNews a lot and lately I've been having some trouble with it.. The code I use is: google_news.get_news("News I want to get"). Normally I get several hundred links a day, now only a few? It seems that he can't find anything anymore, because even if I use the code once for a specific search term, it doesn't find all the news by far?

I've been using the same code for a long time and nothing has changed in the code. I also did not change the version of GNews. I suddenly just got a lot less links?

**Comment by ranahaani** [comment]
Hey, 
Thanks for using GNews, can you please check on google news with the same keywords? All these news are coming from google news.

**Comment by mewmix** [comment]
im not yielding any links right now - same issue no changes to code :(
