### ISSUE TITLE
Optional language option in google_news.language

### ISSUE THREAD

**Issue by Shaun-Tan-DJ** [ranahaani/GNews#59]
Is it possible to not limit the news article by language?
I understand that it defaults to 'en', but it would be helpful to not fix a language so that our search can be less limited.

google_news.language = 'english'  # News in a specific language

**Comment by ranahaani** [comment]
We can limit news articles to a specific language, we can get all languages here 

 `print(google_news.AVAILABLE_LANGUAGES)`
`
