### ISSUE TITLE
Requests dependency too strict and outdated

### ISSUE THREAD

**Issue by phoerious** [ranahaani/GNews#85]
I'm having some trouble installing this package together with other packages without dependencies of other packages.

GNews depends on `requests==2.26.0`. This is a very strict version requirement. Is this really necessary? If not, it would be good to relax the dependency somewhat to something like `requests>=2.26.0,<3.0`. The current requests version is 2.31.0.

**Comment by danilo-css** [comment]
I have built a temporary fork that looses dependencies while the main isn't available: https://github.com/danilo-css/GNews.

You can use it in your project installing it with pip:

```python
pip install --force-reinstall git+https://github.com/danilo-css/GNews.git
```

Or putting this on your requirements.txt:

```python
git+https://github.com/danilo-css/GNews.git
```

**Comment by ranahaani** [comment]
fix here https://github.com/ranahaani/GNews/pull/92
