### ISSUE TITLE
Relax to higher version?

### ISSUE THREAD

**Issue by simprince** [ranahaani/GNews#90]
https://github.com/ranahaani/GNews/blob/701531632570781847f23d76b13bcab0157e0a0a/requirements.txt#L3

Is it possible to use >=? This is causing a conflict in dependency as many packages require a newer version of beautifulsoup.

**Comment by simprince** [comment]
Same on requests==2.26.0 if you could boost this version up or simply use >=

**Comment by anthonyJamRau** [comment]
@simprince @ranahaani 

Is it possible to please use >= in the requests requirement so that it is requests>= 2.26.0 like simprince suggested? I need this for a dependency conflict with the streamlit project here https://pypi.org/project/streamlit/#history

**Comment by ranahaani** [comment]
fix https://github.com/ranahaani/GNews/pull/92
